;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        paredit-kill
        web-mode-element-close
        ))

(setq mc/cmds-to-run-once
      '(
        elpy-shell-send-statement-and-step
        ))
