;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-horizontal-space
        electric-newline-and-maybe-indent
        ess-yank
        eval-expression
        helm-show-kill-ring
        indent-for-tab-command
        insert-pair
        insert-parentheses
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        ))
